apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: pyspark-job-manual
  namespace: default
spec:
  type: Python
  mode: cluster
  image: pyspark-scheduled-job:latest
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///app/job.py
  sparkVersion: "3.1.1"
  driver:
    cores: 1
    memory: "1g"
    serviceAccount: spark-operator-spark
  executor:
    cores: 1
    instances: 1
    memory: "1g"
