apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spark-operator-role
rules:
  - apiGroups:
      - "sparkoperator.k8s.io"
    resources:
      - "scheduledsparkapplications"
      - "sparkapplications"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "delete"
      - "patch"
      - "update"
