image:
  repository: pyspark-scheduled-job  # Use the local Docker image name
  tag: latest

schedule: "*/1 * * * *"   # Runs every hour

sparkJob:
  sparkVersion: "3.1.1"
  driver:
    cores: 1
    memory: "1g"
    serviceAccount: spark-operator-spark
  executor:
    cores: 1
    instances: 1
    memory: "2g"
